Lab1 WOMU/Models/ShoppingCart.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab1_WOMU.Models
{
    public class ShoppingCart
    {

        TankDatabase db = new TankDatabase();
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public string ShoppingCartID { get; set; }
        public const string CartSessionKey = "CartId";
        public virtual ICollection<CartItem> CartItem { get; set; }


        public static ShoppingCart GetCart(HttpContextBase context)
        {
            var cart = new ShoppingCart();
            cart.ShoppingCartID = cart.GetCartId(context);
            return cart;
        }

        // Helper method to simplify shopping cart calls
        public static ShoppingCart GetCart(Controller controller)
        {
            return GetCart(controller.HttpContext);
        }


        /// <summary>
        /// adds the specified product to the cart
        /// </summary>
        /// <param name="Produkt">
        /// id of the product 
        /// </param>
        public void AddToCart(Produkt Produkt)
        {
            var cartItem = db.CartItem.SingleOrDefault(
                c => c.CartId == ShoppingCartID
                && c.ProduktID == Produkt.ProduktID);

            if (cartItem == null) // if no cartItem exists, create a new one
            {
                cartItem = new CartItem
                {
                    ProduktID = Produkt.ProduktID,
                    CartId = ShoppingCartID,
                    Count = 1,
                    DateCreated = DateTime.Now,
                    totPris = Produkt.Pris
                };
                db.CartItem.Add(cartItem);
            }
            //else
            //{
            //    // If the item does exist in the cart then uppdate the quantity
            //    cartItem.Count = cartItem.Count + 1;
            //    cartItem.totPris = cartItem.Count * cartItem.Produkt.Pris;
            //}

            db.SaveChanges();
        }


        /// <summary>
        /// removes the specified product from the cart
        /// </summary>
        /// <param name="id">
        /// id of the product 
        /// </param>
        public void RemoveFromCart(int id)
        {

            var cartItem = db.CartItem.Single(
                cart => cart.CartId == ShoppingCartID
                && cart.ProduktID == id);


            if (cartItem != null)
            {
                db.CartItem.Remove(cartItem);

                db.SaveChanges();
            }
        }

        /// <summary>
        /// Empties the cart
        /// </summary>
        public void EmptyCart()
        {
            var cartItems = db.CartItem.Where(
                cart => cart.CartId == ShoppingCartID);

            foreach (var cartItem in cartItems)
            {
                db.CartItem.Remove(cartItem);
            }
    
            db.SaveChanges();
        }


        /// <summary>
        /// return a list of all cartItems that belong to the cart
        /// </summary>
        /// <returns>
        /// a list of cartItems
        /// </returns>
        public List<CartItem> GetCartItems()
        {
            return db.CartItem.Where(
                cart => cart.CartId == ShoppingCartID).ToList();
        }

        /// <summary>
        /// this function gets the count of all item and sums them
        /// </summary>
        /// <returns>
        /// the sum of all items in the cart
        /// 0 if all entries are null
        /// </returns>
        public int GetCount()
        {
            int? count = (from cartItems in db.CartItem
                          where cartItems.CartId == ShoppingCartID
                          select (int?)cartItems.Count).Sum();

            return count ?? 0;
        }


        /// <summary>
        /// sums up the total price of the cart
        /// </summary>
        /// <returns>
        /// the total price of the cart
        /// </returns>
        public double GetTotal()
        {

            decimal? total = (from cartItems in db.CartItem
                              where cartItems.CartId == ShoppingCartID
                              select (int?)cartItems.Count *
                              cartItems.Produkt.Pris).Sum();
            
            return Convert.ToDouble( total ?? decimal.Zero);
        }

        /// <summary>
        /// creates a list of of related products
        /// </summary>
        /// <returns>
        /// a list of all related products to the products in the cart
        /// </returns>
        public List<Produkt> GetRelatedProdukts()
        {
            List<Produkt> related = new List<Produkt>();

            var cart = GetCartItems();

            List<int> orderIDs = new List<int>();

            foreach (var cartItem in cart)
            {
                var temp = db.OrderRad.Where(o => o.ProduktID == cartItem.ProduktID);

                var temp2 = temp.ToList();

                foreach(var t in temp2)
                {
                    orderIDs.Add(t.OrderID);
                }    
            }

            foreach(var ord in orderIDs)
            {
                var order = db.Order.Where(m => m.OrderID == ord);

                foreach(var o in order)
                {
                    foreach(var rad in o.OrderRader)
                    {
                        related.Add(rad.Produkt);
                    }
                }

            }
            // remove all duplicates
            related = related.Distinct().ToList();

            // removes the products that are in the cart from the related products
            foreach(var i in cart)
            {
                related.Remove(i.Produkt);
            }

            return related;
        }


        
        public string GetCartId(HttpContextBase context)
        {
            if (context.Session[CartSessionKey] == null)
            {
                if (!string.IsNullOrWhiteSpace(context.User.Identity.Name))
                {
                    context.Session[CartSessionKey] =
                        context.User.Identity.Name;
                }
                else
                {
                    
                    Guid tempCartId = Guid.NewGuid();

                    context.Session[CartSessionKey] = tempCartId.ToString();
                }
            }
            return context.Session[CartSessionKey].ToString();
        }
    }

}

Lab1 WOMU/Controllers/KundsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lab1_WOMU.Models;

namespace Lab1_WOMU.Controllers
{
    public class KundsController : Controller
    {
        private TankDatabase db = new TankDatabase();
        
        
       
        // GET: Kunds/Create
        public ActionResult Create()
        {
            return View();
        }


        /// <summary>
        /// saves the customer and the redirects to order create
        /// </summary>
        /// <param name="kund">
        /// 
        /// </param>
        /// <returns>
        /// redirects to order create
        /// </returns>
        // POST: Kunds/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "KundID,FörNamn,Efternamn,PostAdress,PostNr,Ort,Epost,Telefonnummer")] Kund kund)
        {
            if (ModelState.IsValid)
            {
                db.Kund.Add(kund);
                db.SaveChanges();
                return RedirectToAction("Create", "Order");
            }

            return View(kund);
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Lab1 WOMU/Controllers/ProduktController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lab1_WOMU.Models;
using Lab1_WOMU.Models.ViewModels;

namespace Lab1_WOMU.Controllers
{
    public class ProduktController : Controller
    {
        private TankDatabase db = new TankDatabase();

        // GET: Produkt
        public ActionResult Index()
        {
            return View(db.Produkter.ToList());
        }

        // GET: Produkt/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produkt produkt = db.Produkter.Find(id);
            if (produkt == null)
            {
                return HttpNotFound();
            }
            return View(produkt);
        }


        // GET: Produkt
        public ActionResult BuyPage(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produkt produkt = db.Produkter.Find(id);
            if (produkt == null)
            {
                return HttpNotFound();
            }
            return View(produkt);
        }


       

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Lab1 WOMU/Controllers/ShoppingCartController.cs
using Lab1_WOMU.Models;
using Lab1_WOMU.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Lab1_WOMU.Controllers
{
    public class ShoppingCartController : Controller
    {
        private TankDatabase db = new TankDatabase();


        /// <summary>
        /// 
        /// </summary>
        /// <returns>
        /// 
        /// </returns>
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            var viewModel = new ShoppingCartVM
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal() * 1.25,
                RelatedProdukts = cart.GetRelatedProdukts()
            };

            return View(viewModel);
        }


        /// <summary>
        /// 
        /// </summary>
        /// <param name="id">
        /// 
        /// </param>
        /// <returns>
        /// 
        /// </returns>
        // GET: Produkt/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produkt produkt = db.Produkter.Find(id);
            if (produkt == null)
            {
                return HttpNotFound();
            }
            return View(produkt);
        }



        /// <summary>
        /// adds a product to the cart
        /// </summary>
        /// <param name="id">
        /// id of product that is going to be added to the cart
        /// </param>
        /// <returns>
        /// 
        /// </returns>
        // GET: /AddToCart/5
        [HttpPost]
        public ActionResult AddToCart(int id)
        {

            var addedItem = db.Produkter
                .Single(item => item.ProduktID == id);

            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedItem);

            // Display the confirmation message
            var results = new SCconfirmVM
            {
                Message = Server.HtmlEncode(addedItem.ProduktNamn) +
                    " har lagts till i din varukorg",
                CartTotal = cart.GetTotal() * 1.25,
                CartCount = cart.GetCount(),
                ItemCount = 1,
                DeleteId = id,
                totPris = addedItem.Pris * 1
                
            };
            return Json(results);
        }

        /// <summary>
        /// removes a specified product
        /// </summary>
        /// <param name="id">
        /// id of product to be removed
        /// </param>
        /// <returns>
        /// 
        /// </returns>
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            
            
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the Produkt to display confirmation
            var itemName = db.Produkter
                .Single(item => item.ProduktID == id);


            
            cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new SCconfirmVM
            {
                Message = "Alla " + Server.HtmlEncode(itemName.ProduktNamn) +
                    "'s har tagits bort from varukorgen.",
                CartTotal = cart.GetTotal() * 1.25,
                CartCount = cart.GetCount(),
                ItemCount = 0,
                DeleteId = id
                
            };
            return Json(results);
        }
        /// <summary>
        /// adds One CartItem to existing Cartitem in cart. then calculates new values
        /// </summary>
        /// <param name="id">
        ///  ID of CartItem in Cart
        /// </param>
        /// <returns>
        /// return New values for values in CartItem
        /// </returns>
        [HttpPost]
        public ActionResult CountP(int id)
        {
            var Temp = db.CartItem.Single(
               Temp1 => Temp1.CartItemID == id);

            Temp.Count = Temp.Count + 1;
            Temp.totPris = Temp.Produkt.Pris * Temp.Count;
            db.SaveChanges();

            var cart = ShoppingCart.GetCart(this.HttpContext);
            if (Temp.Count <= Temp.Produkt.AntalILager)
            {
                var results = new CountModelView
                {
                    Message = Temp.Produkt.ProduktNamn + " har ändrats till " + Temp.Count + " stcken.",
                    ItemCount = Temp.Count,
                    TotPris = Temp.totPris,
                    CartTotal = cart.GetTotal() * 1.25,
                    CartCount = cart.GetCount(),
                    ItemID = Temp.ProduktID
                    
                    
                };
                db.SaveChanges();
                return Json(results);
            }
            else
            {
                Temp.Count = Temp.Count - 1;
                Temp.totPris = Temp.Produkt.Pris * Temp.Count;
                db.SaveChanges();
                var results = new CountModelView
                {
                    Message = "Inga mer Produkter i Lager.",
                    ItemCount = Temp.Count,
                    TotPris = Temp.totPris,
                    CartTotal = cart.GetTotal() * 1.25,
                    CartCount = cart.GetCount(),
                    ItemID = Temp.ProduktID
                  
                    
                };
                db.SaveChanges();
                return Json(results);
            }


        }
        /// <summary>
        /// removes One CartItem to existing Cartitem in cart. then calculates new values
        /// </summary>
        /// <param name="id"> 
        /// ID of CartItem in Cart
        /// </param>
        /// <returns>
        /// return New values for values in CartItem
        /// </returns> 
        public ActionResult CountM(int id)
        {
            {
                var Temp = db.CartItem.Single(
                Temp1 => Temp1.CartItemID == id);

                Temp.Count = Temp.Count - 1;
                Temp.totPris = Temp.Produkt.Pris * Temp.Count;
                db.SaveChanges();

                
                var cart = ShoppingCart.GetCart(this.HttpContext);

                if (Temp.Count > 0)
                {
                    // Display the confirmation message
                    var results = new CountModelView
                    {
                        Message = ("En " + Temp.Produkt.ProduktNamn + " har tagits bort från din varukorg."),
                        ItemCount = Temp.Count,
                        CartTotal = cart.GetTotal() * 1.25,
                        CartCount = cart.GetCount(),
                        ItemID = Temp.ProduktID,
                        TotPris = getCartItemTotalPris(Temp)
                    };
                    db.SaveChanges();
                    return Json(results);
                }
                else
                {
                    Temp.Count = Temp.Count + 1;
                    Temp.totPris = Temp.Produkt.Pris * Temp.Count;
                    db.SaveChanges();
                    cart.RemoveFromCart(Temp.ProduktID); 
                    var results = new CountModelView
                    {
                        Message = (Temp.Produkt.ProduktNamn + " har tagits bort från din varukorg."),
                        CartTotal = cart.GetTotal() * 1.25,
                        CartCount = cart.GetCount(),
                        ItemID = Temp.ProduktID,
                        TotPris = Temp.totPris
                    };
                    db.SaveChanges();
                    return Json(results);
                }
            }
            }
        public int getCartItemTotalPris(CartItem item)
        {
            var pris = item.Count * item.Produkt.Pris;
            
            return (pris);
        }
    }
}

Lab1 WOMU/Views/ShoppingCart/Details.cshtml
<h2>Details</h2>

@model Lab1_WOMU.Models.Produkt

@{
    ViewBag.Title = "Detaljer";
}



<div>
    <h4>Produkt</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProduktID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProduktID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProduktNamn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProduktNamn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProduktBeskrivning)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProduktBeskrivning)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Pris)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pris)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AntalILager)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AntalILager)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Tillbaka till varukorg", "Index")
</p>

Lab1 WOMU/Views/ShoppingCart/Index.cshtml
@model Lab1_WOMU.Models.ViewModels.ShoppingCartVM
@{
    ViewBag.Title = "Shopping Cart";
}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script type="text/javascript">
    $(function () {
        // Document.ready -> link up remove event handler
        $(".RemoveLink").click(function () {
            // Get the id from the link
            var recordToDelete = $(this).attr("data-id");
            if (recordToDelete != '') {
                // Perform the ajax post
                $.post("/ShoppingCart/RemoveFromCart", { "id": recordToDelete },
                    function (data) {
                        // Successful requests get here
                        // Update the page elements
                        if (data.ItemCount == 0) {
                            $('#row-' + data.DeleteId).fadeOut('slow');
                        } else {
                            $('#item-count-' + data.DeleteId).text(data.ItemCount);
                            
                        }
                        $('#item-pris-'+data.ItemID).text(data.totPris);
                        $('#cart-total').text(data.CartTotal);
                        $('#update-message').text(data.Message);
                        $('#cart-status').text(data.CartCount);
                    });
            }
        });
    });
</script>
<script type="text/javascript">
    $(function () {
        // Document.ready -> link up remove event handler
        $(".CountM").click(function () {
            // Get the id from the link
            var recordToDelete = $(this).attr("data-id");
            if (recordToDelete != '') {
                // Perform the ajax post
                $.post("/ShoppingCart/CountM", { "id": recordToDelete },
                    function (data) {
                        // Successful requests get here
                        // Update the page elements
                        if (data.ItemCount == 0) {
                            $('#row-' + data.ItemID).fadeOut('slow');
                        } else {
                            $('#item-count-' + data.ItemID).text(data.ItemCount);
                            $('#item-pris-'+data.ItemID).text(data.TotPris);
                        }
                       
                        $('#cart-total').text(data.CartTotal);
                        $('#update-message').text(data.Message);
                        $('#cart-status').text(data.CartCount);
                    });
            }
        });
    });

</script>
<script type="text/javascript">
    $(function () {
        $(".CountP").click(function () {
            // Get the id from the link
            var recordToAdd = $(this).attr("data-id");
            if (recordToAdd != '') {
                // Perform the ajax post
                $.post("/ShoppingCart/CountP", { "id": recordToAdd },
                    function (data) {
                        // Successful requests get here
                        // Update the page elements
                        
                        $('#item-count-'+data.ItemID).text(data.ItemCount);
                        $('#cart-total').text(data.CartTotal);
                        $('#update-message').text(data.Message);
                        $('#cart-status').text(data.CartCount);
                        $('#item-pris-'+data.ItemID).text(data.TotPris);
                    });
            }
        });
    });
</script>
<h3>
    <em>Översikt</em> 
</h3>

@{

    if (Model.CartItems.Count > 0)
    {
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Order Samanfattning</h3>
            </div>
            <div class="panel-body">

                <div id="update-message">
                </div>
                <table class="table table-striped table-hover ">
                    <thead>
                        <tr>
                            <th>
                                Produkt Namn
                            </th>
                            <th>
                                Styck Pris (exkl. moms)
                            </th>
                            <th>
                                Antal
                            </th>
                            <th>
                                Total Pris (exkl. moms)
                            </th>
                            <th>
                                Ändra Antal
                            </th>
                            <th>
                                Ta Bort Vara
                            </th>
                            <th>
                                Total pris på varukorg (inkl. moms)
                            </th>
                        </tr>
                    </thead>
                    @foreach (var item in Model.CartItems)
                    {
                        <tr id="row-@item.ProduktID">
                            <td>
                                @Html.ActionLink(item.Produkt.ProduktNamn, "Details", "ShoppingCart", new { id = item.ProduktID }, null)
                            </td>
                            <td>
                                @item.Produkt.Pris
                            </td>
                            <td id="item-count-@item.ProduktID">
                                @item.Count
                            </td>
                            <td id="item-pris-@item.ProduktID">
                             @item.totPris
                            </td>
                            <td>
                                <a href="#" class="CountP"
                                   data-id="@item.CartItemID">
                                    +
                                </a>
                                <a href="#" class="CountM"
                                   data-id="@item.CartItemID">
                                    -
                                </a>
                            </td>
                           
                            <td>
                                <a href="#" class="RemoveLink"
                                   data-id="@item.ProduktID">
                                    Ta bort
                                    Från Varukorg
                                </a>
                            </td>
                        </tr>
                    }
                    <tr class="info">
                        <td>
                            Total
                        </td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td id="cart-total">
                            @Model.CartTotal
                        </td>
                    </tr>
                </table>


                <table>
                    <tr>
                        <th>
                            Relaterade Produkter
                        </th>
                        @foreach (var prod in Model.RelatedProdukts)
                        {
                            <td>
                                @Html.ActionLink(prod.ProduktNamn, "Details", "Produkt", new { id = prod.ProduktID }, null)
                            </td>
                        }
                    </tr>
                </table>

                <button type="button" class="btn btn-success btn-sm" onclick="location.href='@Url.Action("Create", "Kunds")'">
                    Check Out &raquo;
                </button>
            </div>
        </div>
    }
    else
    {
        <div>
            <p>
                Det finns inga varor i din varukorg. Var snäll och lägg till varor i varukorgen
            </p>
        </div>
    }
}